AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL
    

Resources:
  WhatsAppWebHookLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "EventAssistant-WhatsAppWebhook"
      Description: "Event Assistant webhook"
      Handler: "index.handler"
      Runtime: nodejs18.x
      Environment: 
        Variables: 
            VERIFY_TOKEN: "OVERRIDE"
            WHATSAPP_TOKEN: "OVERRIDE"
      Timeout: 3
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      CodeUri: .
      Architectures: 
        - "arm64"
      AutoPublishAliasAllProperties: false
      AutoPublishAlias: live
      DeploymentPreference:
        Enabled: true
        Type: Canary10Percent5Minutes
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 10000
            PayloadFormatVersion: '1.0'

  WebHookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: messages
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "type"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "id"
          KeyType: HASH
        - 
          AttributeName: "type"
          KeyType: RANGE

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'EventAssistant-WhatsAppWebhook-Execution'
      Description: Creating service role in IAM for AWS Lambda
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      Policies: 
        - PolicyName: LambdaCustomExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:BatchWriteItem'
                  - 'dynamodb:ConditionCheckItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'